
import matplotlib.pyplot as plt

n=int(input("Enter the number of People: "))
count_people=0
sum1=0
count_grace=0
count_not_grace=0
l_grace=[]
l_no_grace=[]
l_fine=[]
l_annual_grace=[]
l_annual_no_grace=[]
for i in range(n):
    bank_balance=int(input("Enter the bank balance: "))
    ann_income=int(input("Enter the annual income: "))
    e=True
    while e==True:
        emp=input("Enter the Employment type: ")
        if emp in ['Employed','Unemployed']:
            e=False
        else:
            print("Please enter the right employment type.")
            e=True
    t=(ann_income>100000 and bank_balance>5000)
    if (emp=="Employed"):
        if t==True:
            grace_period=15
            count_people+=1
            count_grace+=1
            l_grace.append(bank_balance)
            l_annual_grace.append(ann_income)
        elif t==False:
            count_not_grace+=1
            l_no_grace.append(bank_balance)
            l_annual_no_grace.append(ann_income)
            for i in range(1,16): #Fine for 15 days
                fine=((2.5/100)*i*bank_balance)
                bank_balance-=fine
                sum1+=fine
                l_fine.append(sum1)
    elif (emp=="Unemployed"):
        count_grace+=1
        l_grace.append(bank_balance)
        l_annual_grace.append(ann_income)
        
#PART A
print() #Leaves a Line for Presentation purposes only.
print("The total number of people who were given a grace period of exactly 15 days were: ",count_people)

#PART B
print()
if l_fine!=[]:
    print("The maximum fine that can be levied by the bank in the period of 15 days is: ",max(l_fine))
else:
    print("Their is no fine levied as all the people are 'Unemployed \nOR \n 'they have a bank balance and annual income greater than 100000 and 5000 respectively'.")

#PART C
print()
print("The total amount being generated by the bank as part of the fine is: ",sum(l_fine))

#PART D
print()
plt.plot(l_grace,label="Eligible for Grace")
plt.plot(l_no_grace,label="Not Eligible for Grace")
plt.ylabel("Bank Balance")
plt.legend()
plt.title("Bank Balance Difference Graph")
plt.show()

#PART E
print()
s=sum(l_grace)
print("The original value is: ",s)
if count_grace%2==0:
    a=int(count_grace/2)
    med=(l_grace[a-1]+l_grace[a])/2
else:
    a=int((count_grace+1)/2)
    med=l_grace[a-1]
print("The median of the bank balance is: ",med)
print("The difference of the median from the original is: ",s-med)

#PART F
print()
plt.plot(l_annual_grace,label="Eligible for Grace")
plt.plot(l_annual_no_grace,label="Not Eligible for Grace")
plt.ylabel("Annual Income")
plt.title("Annual Income Difference Graph")
plt.legend()
plt.show()

